name: Ruff Linting & Formatting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
    
permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          
      - name: Run Ruff linter
        run: |
          ruff check .
          
      - name: Run Ruff formatter
        run: |
          ruff format . --check
          
      # Optional: Add this step if you want to automatically fix formatting issues
      - name: Fix formatting issues
        if: failure()
        run: |
          ruff format .
      
